<? $time_now = "1372841029";  return $task_list =array (
  0 => 
  array (
    'id' => '100',
    'task_name' => 'APO-清除发布日志',
    'task_desc' => 'apollo-清除发布日志',
    'task_content' => 'sudo -u www /bin/bash -c \'/bin/rm -fr /data/Data/logs/*-*.log\'',
    'expected_execution_time' => '600',
    'task_interval' => '023***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-apollo-web-02',
  ),
  1 => 
  array (
    'id' => '102',
    'task_name' => 'APO-同步sim环境',
    'task_desc' => 'apollo-同步sim环境',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/php /data/webapp/Release/App/Script/rsyncOnlineAndV3ToBJSim.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-apollo-web-02',
  ),
  2 => 
  array (
    'id' => '103',
    'task_name' => 'APO-OA用户同步',
    'task_desc' => 'apollo-OA用户同步',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/php /data/Script/SyncOaUser/App/subsys_sync/syncUsers.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '301***',
    'sudo_user' => 'www',
    'hostlist' => 'jxq-oa-web-01',
  ),
  3 => 
  array (
    'id' => '104',
    'task_name' => 'APO-同步内网UC用户',
    'task_desc' => 'apollo-同步内网UC用户',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/php /data/Script/SyncOaUser/App/subsys_sync/syncUcUser.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '02***',
    'sudo_user' => 'www',
    'hostlist' => 'jxq-oa-web-01',
  ),
  4 => 
  array (
    'id' => '105',
    'task_name' => 'APO-同步微博用户',
    'task_desc' => 'apollo-同步微博用户',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/php /data/Script/SyncOaUser/App/subsys_sync/syncWBuser.php\'',
    'expected_execution_time' => '900',
    'task_interval' => '152***',
    'sudo_user' => 'www',
    'hostlist' => 'jxq-oa-web-01',
  ),
  5 => 
  array (
    'id' => '106',
    'task_name' => 'APO-微博通知',
    'task_desc' => 'apollo-微博通知',
    'task_content' => 'sudo -u www /bin/bash -c \'cd /data/Script/im_notice ; /bin/bash im_notice.sh\'',
    'expected_execution_time' => '900',
    'task_interval' => '*/209,12,13,19,20,21,22***',
    'sudo_user' => 'www',
    'hostlist' => 'jxq-oa-web-01',
  ),
  6 => 
  array (
    'id' => '107',
    'task_name' => 'APO-同步配置文件',
    'task_desc' => 'apollo-同步配置文件',
    'task_content' => 'sudo -u apollo /bin/bash -c \'/data/apollo/lampp/bin/php /data/apollo/apollo_agent/Scr/checkConf.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'apollo',
    'hostlist' => 'jxq-sys-dns-03,nh-hps-fr-a01,yz-apollo-web-02',
  ),
  7 => 
  array (
    'id' => '108',
    'task_name' => 'MSC-全国页面',
    'task_desc' => '全国页面生成',
    'task_content' => '/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/common/tuiguang_category/MsTuiguangCategory.php run',
    'expected_execution_time' => '13000',
    'task_interval' => '103***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-sys-bak-04',
  ),
  8 => 
  array (
    'id' => '109',
    'task_name' => 'MYAD-定向-Redis缓存检查',
    'task_desc' => '检查定向redis缓存',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/dev/sticky/self_direction_util.php checkcache\'',
    'expected_execution_time' => '600',
    'task_interval' => '01***',
    'sudo_user' => 'ganji',
    'hostlist' => 'nh-ms-web-sim01,yz-sys-bak-04',
  ),
  11 => 
  array (
    'id' => '112',
    'task_name' => 'OA-个人软件未申报邮件通知',
    'task_desc' => '个人软件未申报邮件通知',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/curl http://i.corp.ganji.com/Software/EmailNoSoftwareUser/userSoftwareNoApplyEmail -s\'',
    'expected_execution_time' => '600',
    'task_interval' => '1012***',
    'sudo_user' => 'www',
    'hostlist' => 'jxq-oa-web-01',
  ),
  12 => 
  array (
    'id' => '113',
    'task_name' => 'OA-下属软件未申报邮件通知',
    'task_desc' => '下属软件未申报邮件通知',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/curl http://i.corp.ganji.com/Software/EmailNoSoftwareUser/subordinateSoftwareNoApplyEmail -s\'',
    'expected_execution_time' => '600',
    'task_interval' => '1512***',
    'sudo_user' => 'www',
    'hostlist' => 'jxq-oa-web-01',
  ),
  13 => 
  array (
    'id' => '114',
    'task_name' => 'OA-将oa视图转换成oa表',
    'task_desc' => '将oa中的ad视图转换成ad表',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/curl http://i.corp.ganji.com/Software/Public/adViewToadTableNoEcho\'',
    'expected_execution_time' => '600',
    'task_interval' => '102***',
    'sudo_user' => 'www',
    'hostlist' => 'jxq-oa-web-01',
  ),
  14 => 
  array (
    'id' => '115',
    'task_name' => 'MYAD-置顶-服务小类推广更新修改后的地标',
    'task_desc' => '服务小类推广更新修改后的地标',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/update_substicky_geo.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/30****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  15 => 
  array (
    'id' => '116',
    'task_name' => 'MYAD-小类-未使用提醒短信',
    'task_desc' => '小类推广未使用提醒短信',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/send_substicky_sms.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '010***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  16 => 
  array (
    'id' => '117',
    'task_name' => 'MYAD-后台-联盟-收入',
    'task_desc' => '自助后台-联盟广告-收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/union_ad_report_import.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  17 => 
  array (
    'id' => '120',
    'task_name' => 'MYAD-后台-置顶-历史收入',
    'task_desc' => '自助后台-自助置顶-历史收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_sticky_report_import.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '06***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  18 => 
  array (
    'id' => '121',
    'task_name' => 'MYAD-后台-置顶-收入',
    'task_desc' => '自助后台-自助置顶-今日收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_sticky_report_import.php today\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  19 => 
  array (
    'id' => '122',
    'task_name' => 'MYAD-后台-置顶-在线',
    'task_desc' => '自助后台-自助置顶-在线',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_sticky_online_import.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-sim00',
  ),
  21 => 
  array (
    'id' => '125',
    'task_name' => 'MYAD-刷新-收入',
    'task_desc' => '自助后台-自助刷新-收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_refresh_report_import.php\'',
    'expected_execution_time' => '5400',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-sim00',
  ),
  22 => 
  array (
    'id' => '126',
    'task_name' => 'MYAD-端口-收入',
    'task_desc' => '自助后台-自助端口-收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_premier_report_import.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  23 => 
  array (
    'id' => '127',
    'task_name' => 'MYAD-后台-定向-收入',
    'task_desc' => '自助后台-定向推广-收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_direction_report_import.php today\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  24 => 
  array (
    'id' => '128',
    'task_name' => 'MYAD-后台-定向-历史收入',
    'task_desc' => '自助后台-定向推广-历史收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_direction_report_import.php\'',
    'expected_execution_time' => '900',
    'task_interval' => '06***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  26 => 
  array (
    'id' => '130',
    'task_name' => 'MYAD-后台-定向-点击',
    'task_desc' => '自助后台-定向推广-点击',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_direction_click_import.php\'',
    'expected_execution_time' => '15000',
    'task_interval' => '09***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  27 => 
  array (
    'id' => '131',
    'task_name' => 'MYAD-后台-小类-收入',
    'task_desc' => '自助后台-小类推广-收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_substicky_report_import.php today\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  28 => 
  array (
    'id' => '132',
    'task_name' => 'MYAD-后台-竞价-点击',
    'task_desc' => '自助后台-自助竞价-点击',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_bidding_click_import.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '08***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  29 => 
  array (
    'id' => '133',
    'task_name' => 'MYAD-后台-竞价-收入',
    'task_desc' => '自助后台-自助竞价-收入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_bidding_report_import.php today\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  30 => 
  array (
    'id' => '134',
    'task_name' => 'MYAD-后台-置顶-点击',
    'task_desc' => '自助后台-自助置顶-点击',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_sticky_click_import.php yesterday\'',
    'expected_execution_time' => '3600',
    'task_interval' => '07***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  31 => 
  array (
    'id' => '135',
    'task_name' => 'MYAD-竞价-审核队列',
    'task_desc' => '自助竞价-审核队列',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_bidding/audit_ad_queue.php\'',
    'expected_execution_time' => '650',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  32 => 
  array (
    'id' => '136',
    'task_name' => 'MYAD-置顶-Redis数据同步',
    'task_desc' => '自助置顶-Redis数据同步',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/q4m_redis.php sticky\'',
    'expected_execution_time' => '4000',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'nh-ms-web-sim01,yz-sys-bak-04',
  ),
  33 => 
  array (
    'id' => '137',
    'task_name' => 'MYAD-定向-审核队列',
    'task_desc' => '定向推广-审核队列',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_direction/audit_ad_queue.php\'',
    'expected_execution_time' => '1800',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  34 => 
  array (
    'id' => '138',
    'task_name' => 'MYAD-公共-上海机房Redis操作',
    'task_desc' => '自助上海机房读队列操作上海机房的redis',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_service/q4m_redis.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'nh-ms-web-sim01',
  ),
  35 => 
  array (
    'id' => '139',
    'task_name' => 'MYAD-端口-购买后两日后公司认证状态未认证自动退费',
    'task_desc' => '自助端口-购买后两日后公司认证状态为未上传、审核不通过的自动退费
MYAD-2495',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_premier/check_wanted_premier_auth.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '023***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  36 => 
  array (
    'id' => '140',
    'task_name' => 'MYAD-置顶-Event处理',
    'task_desc' => '自助服务-Event处理',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/post_order_event/self_top_status_change_event.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  37 => 
  array (
    'id' => '142',
    'task_name' => 'MYAD-置顶-Event检查',
    'task_desc' => '自助置顶检查event表未处理数据过多',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/post_order_event/self_top_status_change_event.php check\'',
    'expected_execution_time' => '1000',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  38 => 
  array (
    'id' => '143',
    'task_name' => 'MYAD-置顶-发送优惠码',
    'task_desc' => '自助置顶-发送优惠码',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/send_youhui_code.php edm_webim_sms\'',
    'expected_execution_time' => '900',
    'task_interval' => '09***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  39 => 
  array (
    'id' => '144',
    'task_name' => 'MYAD-定向-发送优惠码',
    'task_desc' => '定向推广-发送优惠码',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/send_youhui_code_for_self_direction.php edm_webim_sms\'',
    'expected_execution_time' => '600',
    'task_interval' => '09***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  40 => 
  array (
    'id' => '145',
    'task_name' => 'MYAD-竞价-排名脚本',
    'task_desc' => '自助竞价-排名脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_bidding/biddingRank.cron.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '3017***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-sim00',
  ),
  41 => 
  array (
    'id' => '146',
    'task_name' => 'MYAD-竞价-上线脚本',
    'task_desc' => '自助竞价-上线脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_bidding/biddingPostOnline.cron.php yesterday\'',
    'expected_execution_time' => '600',
    'task_interval' => '100***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-sim00',
  ),
  42 => 
  array (
    'id' => '147',
    'task_name' => 'MYAD-竞价-连续竞价',
    'task_desc' => '自助竞价-连续竞价',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_bidding/biddingInitOrder.cron.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '03***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-sim00',
  ),
  43 => 
  array (
    'id' => '148',
    'task_name' => 'MYAD-端口-房产账号同步',
    'task_desc' => '自助端口-房产账号同步',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/dev/self_premier/house_account_sync.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  44 => 
  array (
    'id' => '149',
    'task_name' => 'MYAD-置顶-在线数据 for CRM',
    'task_desc' => '自助置顶-在线数据 for CRM',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/push_online_order.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '02***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  45 => 
  array (
    'id' => '150',
    'task_name' => 'MYAD-置顶-清理无效订单',
    'task_desc' => '自助置顶-清理无效订单',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/order_check_for_delete.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '00*/1**',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  46 => 
  array (
    'id' => '151',
    'task_name' => 'MYAD-置顶-招聘自动取消订单',
    'task_desc' => '自助置顶招聘自动取消订单',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/auto_cancel_order.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  47 => 
  array (
    'id' => '153',
    'task_name' => 'MYAD-置顶-招聘公司认证状态',
    'task_desc' => '自助置顶-招聘公司认证状态',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/order_check_for_wanted_company.php\'',
    'expected_execution_time' => '800',
    'task_interval' => '*/20****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  48 => 
  array (
    'id' => '154',
    'task_name' => 'MYAD-刷新-高级刷新上线',
    'task_desc' => '高级刷新：普通帖子变为端口帖子',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/check_gaoji_refresh.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  49 => 
  array (
    'id' => '155',
    'task_name' => 'MYAD-定向-招聘公司认证',
    'task_desc' => '定向推广-招聘公司认证',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_direction/order_check_for_wanted_company.php\'',
    'expected_execution_time' => '800',
    'task_interval' => '*/20****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  50 => 
  array (
    'id' => '156',
    'task_name' => 'MYAD-小类-订单检查',
    'task_desc' => '小类推广',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/check_substicky_order.php\'',
    'expected_execution_time' => '1200',
    'task_interval' => '*/30****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  51 => 
  array (
    'id' => '157',
    'task_name' => 'SEC-【二手帮帮】刷新脚本',
    'task_desc' => '帮帮刷新脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/tuiguang/secondhand_bang/cron/RefreshBangAdsListByUserSet.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-tg-web-02',
  ),
  52 => 
  array (
    'id' => '160',
    'task_name' => 'SEC-【狗保障平台】订单取消',
    'task_desc' => '一定时间内订单未成功，则取消',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/trade_pet/order_cancel.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  53 => 
  array (
    'id' => '161',
    'task_name' => 'SEC-【狗保障平台】订单过保障期',
    'task_desc' => '超过保障期，则订单改变状态',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/trade_pet/over_insurance.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  55 => 
  array (
    'id' => '164',
    'task_name' => 'CHE-【车辆帮帮】自动刷新脚本',
    'task_desc' => '车辆店铺自动刷新脚本',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/tuiguang/vehicle_bang/cron/refresh_post.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/10****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-tg-web-02',
  ),
  56 => 
  array (
    'id' => '165',
    'task_name' => 'CHE-【车辆帮帮】帮帮过期下线推广',
    'task_desc' => '车辆店铺帮帮过期下线推广',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/tuiguang/vehicle_bang/cron/clean_up_recommend_post.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/10****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  57 => 
  array (
    'id' => '166',
    'task_name' => 'MYAD-刷新-预约刷新',
    'task_desc' => '自助预约刷新',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_refresh/order_yuyue_refresh.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  58 => 
  array (
    'id' => '167',
    'task_name' => 'CHE-【车辆帮帮】刷新日志归档脚本',
    'task_desc' => '车辆店铺刷新日志归档脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/tuiguang/vehicle_bang/cron/import_from_vehicle_refresh_log.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '02***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  59 => 
  array (
    'id' => '168',
    'task_name' => 'APO-临时监控脚本',
    'task_desc' => '临时监控脚本，mc redis',
    'task_content' => 'sudo -u www /bin/bash -c \'/data/apollo/lampp/bin/php /data/apollo/apollo_agent/Scr/checkMonitorSimple.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '0*/2***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-apollo-web-02',
  ),
  60 => 
  array (
    'id' => '170',
    'task_name' => 'MYAD-定向-CTR Build脚本',
    'task_desc' => '定向推广-CTR Build脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_direction_rank_build.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '012***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  61 => 
  array (
    'id' => '171',
    'task_name' => 'MYAD-营销-EventImport',
    'task_desc' => '营销-EventImport',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/promotion/cron/marketing_event_import.php\'',
    'expected_execution_time' => '2000',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  62 => 
  array (
    'id' => '172',
    'task_name' => 'MYAD-营销-EventSend',
    'task_desc' => '市场营销-EventSend',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/promotion/cron/marketing_event_send.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  63 => 
  array (
    'id' => '175',
    'task_name' => 'MYAD-公共-检查redis的队列堆积',
    'task_desc' => '检查redis的队列堆积',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_service/check_q4m_data.php\'',
    'expected_execution_time' => '1000',
    'task_interval' => '08-22***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  64 => 
  array (
    'id' => '176',
    'task_name' => 'CHE-认证帖子定期刷新',
    'task_desc' => '认证帖子定期刷新',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/renzheng_refresh_post.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '07-23***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  65 => 
  array (
    'id' => '178',
    'task_name' => 'MYAD-置顶-未下线检查',
    'task_desc' => '置顶-未下线检查',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/post_check_for_offline.php\'',
    'expected_execution_time' => '900',
    'task_interval' => '00*/1**',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  66 => 
  array (
    'id' => '180',
    'task_name' => 'SEC-【宜搜】二手车辆抓取数据提供脚本（大城市）',
    'task_desc' => '宜搜二手车辆抓取数据提供脚本【大城市】',
    'task_content' => 'sudo -u www /bin/bash -c \'/bin/bash /usr/local/shell/yisoubig.sh\'',
    'expected_execution_time' => '900',
    'task_interval' => '00,12***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  67 => 
  array (
    'id' => '181',
    'task_name' => 'SEC-【宜搜】二手车辆抓取数据提供脚本（小城市）',
    'task_desc' => '宜搜二手车辆抓取数据提供脚本【小城市】',
    'task_content' => 'sudo -u www /bin/bash -c \'/bin/bash /usr/local/shell/yisoucommon.sh\'',
    'expected_execution_time' => '15400',
    'task_interval' => '00***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  71 => 
  array (
    'id' => '186',
    'task_name' => 'MYAD-置顶-过期下线',
    'task_desc' => '置顶过期下线脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/order_check_for_expire.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  72 => 
  array (
    'id' => '187',
    'task_name' => 'MYAD-置顶-在线检查',
    'task_desc' => '置顶在线贴状态检查',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/sticky/post_check_for_online.php\'',
    'expected_execution_time' => '900',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  73 => 
  array (
    'id' => '190',
    'task_name' => 'ZUCHE--车源索引建立及刷新脚本',
    'task_desc' => '车源索引建立及刷新脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/zuche/cron/unit_test_cron.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  74 => 
  array (
    'id' => '191',
    'task_name' => 'ZUCHE-61-商家及车辆得分定时统计脚本',
    'task_desc' => '商家及车辆得分定时统计脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/zuche/cron/ZucheComputeScore.class.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/30****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  75 => 
  array (
    'id' => '192',
    'task_name' => 'ZUCHE-租车订单状态相关短信提醒',
    'task_desc' => '租车订单状态相关短信提醒',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/zuche/cron/zuche_sms.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  76 => 
  array (
    'id' => '193',
    'task_name' => 'ZUCHE-将已支付订单转入结算计划队列',
    'task_desc' => '将已支付订单转入结算计划队列',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/zuche/cron/zuche_settle_payment.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  77 => 
  array (
    'id' => '194',
    'task_name' => 'ZUCHE-将结算计划转为运营人员可操作结算的数据',
    'task_desc' => '将结算计划转为运营人员可操作结算的数据，从计划表转到运营后台可实际处理的数据表中。',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/zuche/cron/zuche_settle.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  78 => 
  array (
    'id' => '195',
    'task_name' => 'ZUCHE-租车每日凌晨统计数据脚本',
    'task_desc' => '租车每日凌晨统计数据脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/zuche/cron/run_for_daily.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '251***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  79 => 
  array (
    'id' => '196',
    'task_name' => 'ZUCHE-根据事件触发整理短信到短信发送队列',
    'task_desc' => '根据事件触发整理短信到短信发送队列, 不负责发送',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/zuche/cron/zuche_trigger_sms.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  80 => 
  array (
    'id' => '197',
    'task_name' => 'ZUCHE-每日上午投诉处理结果通知',
    'task_desc' => '每日上午投诉处理结果通知',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/zuche/cron/zuche_complain_sms.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '019***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  81 => 
  array (
    'id' => '198',
    'task_name' => 'FUWU-服务、教育帮帮下线脚本',
    'task_desc' => '服务、教育帮帮下线脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/cron_bang_sticky_expire.php\'',
    'expected_execution_time' => '900',
    'task_interval' => '351***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  82 => 
  array (
    'id' => '199',
    'task_name' => 'FUWU-店铺点击数统计',
    'task_desc' => '店铺点击数统计',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/service_store/PageShowDataTongji.class.php > /dev/null\'',
    'expected_execution_time' => '900',
    'task_interval' => '3502**0',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  83 => 
  array (
    'id' => '200',
    'task_name' => 'FUWU-装修招投标过期下线脚本',
    'task_desc' => '装修招投标过期下线脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/fitment_tender_expire.php > /dev/null\'',
    'expected_execution_time' => '600',
    'task_interval' => '3001***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  85 => 
  array (
    'id' => '202',
    'task_name' => 'FUWU-装修定向标过期脚本',
    'task_desc' => '装修定向标过期脚本，正常有效期期为1小时，为用户预留1小时，每十分钟跑一次，有效期实际最长2小时十分钟',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/fitment_orient.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/10****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  86 => 
  array (
    'id' => '203',
    'task_name' => 'FUWU-装修、问答等相关pv统计',
    'task_desc' => '装修、问答等相关pv统计',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/fitment_pv.php > /dev/null\'',
    'expected_execution_time' => '1800',
    'task_interval' => '0110,18***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  87 => 
  array (
    'id' => '204',
    'task_name' => 'FUWU-装修相关审核任务发起脚本',
    'task_desc' => '装修相关审核任务发起脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/fitment_2_emp.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  88 => 
  array (
    'id' => '205',
    'task_name' => 'FUWU-装修问题审核结果处理脚本',
    'task_desc' => '装修问题审核结果处理脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/fitment_ask.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/10****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  89 => 
  array (
    'id' => '206',
    'task_name' => 'FUWU-装修招标相关短信通知',
    'task_desc' => '装修招标相关短信通知',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/fitment_sms.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '0210,12,14,16,18***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  90 => 
  array (
    'id' => '207',
    'task_name' => 'HPS-充值收入每日报表',
    'task_desc' => '统计充值收入每日报表，发送邮件',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/pay/cron/pay_report_daliy_v2.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '03***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  91 => 
  array (
    'id' => '208',
    'task_name' => 'HPS-自动补单脚本',
    'task_desc' => '支付自动补单',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/pay/cron/auto_confirm.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/10****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  92 => 
  array (
    'id' => '209',
    'task_name' => 'HPS-支付宝代付结果文件下载并回调业务线',
    'task_desc' => '对每天支付宝代付结果文件进行查询和下载，并根据文件内容回调业务线',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/pay/cron/alipay_dfk_result.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '06***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  93 => 
  array (
    'id' => '210',
    'task_name' => 'CHE-【车辆帮帮】定期重置bang_name',
    'task_desc' => '遍历bang_company，将bang_name_status=-1的bang_name置空',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/tuiguang/vehicle_bang/cron/remove_bang_name.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/10****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  95 => 
  array (
    'id' => '212',
    'task_name' => 'FANG-周边小区',
    'task_desc' => '生成小区的周边小区',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/gen_xiaoqu_near.php > /dev/null\'',
    'expected_execution_time' => '86400',
    'task_interval' => '002*/1*',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  97 => 
  array (
    'id' => '214',
    'task_name' => 'SEC-【自动刷新】三线城市刷新',
    'task_desc' => '三线城市七天前或14天前帖子刷新',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/secondmarket/AutoRefreshPostForCity.class.php\'',
    'expected_execution_time' => '4000',
    'task_interval' => '04***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  98 => 
  array (
    'id' => '215',
    'task_name' => 'FUWU-装修案例、家政商品化审核处理',
    'task_desc' => '装修发布案例及家政商品化审核处理',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/emp_2_fw_queue.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/6****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  99 => 
  array (
    'id' => '216',
    'task_name' => 'CHE-【车辆帮帮】过期帮帮帖子去掉标识',
    'task_desc' => '过期帮帮帖子去掉标识',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/clean_up_bang.php\'',
    'expected_execution_time' => '5400',
    'task_interval' => '01***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  100 => 
  array (
    'id' => '217',
    'task_name' => 'FUWU-服务店铺帮帮审核结果处理',
    'task_desc' => '服务店铺帮帮审核结果处理',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/crm_2_fuwu_audit_queue.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/6****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  103 => 
  array (
    'id' => '220',
    'task_name' => 'CHE-【车辆帮帮】没有正确被标识的店铺帖子修复',
    'task_desc' => '没有正确被标识的店铺帖子修复',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/fix_ershouche_posttype.php\'',
    'expected_execution_time' => '800',
    'task_interval' => '*/30****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  104 => 
  array (
    'id' => '221',
    'task_name' => 'CHE-【新车】车系同价位推荐',
    'task_desc' => '车系同价位推荐',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/xinche_series_price_recommend.php\'',
    'expected_execution_time' => '5400',
    'task_interval' => '02***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  105 => 
  array (
    'id' => '222',
    'task_name' => 'CHE-【新车】同品牌其他车系推荐',
    'task_desc' => '同品牌其他车系推荐',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/xinche_series_same_recommend.php\'',
    'expected_execution_time' => '5400',
    'task_interval' => '02***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  106 => 
  array (
    'id' => '223',
    'task_name' => 'CHE-【车辆大类首页】最受关注排行数据',
    'task_desc' => '生成大类首页右侧，最受关注排行数据',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/dev/vehicle/get_sell_num.php\'',
    'expected_execution_time' => '40000',
    'task_interval' => '01***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  107 => 
  array (
    'id' => '224',
    'task_name' => 'CHE-【273合作】帖子导入',
    'task_desc' => '273的帖子导入',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/msapi/cron/ershouchePublish.php\'',
    'expected_execution_time' => '5400',
    'task_interval' => '0****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  109 => 
  array (
    'id' => '226',
    'task_name' => 'FUWU-教育培训付费帖子刷新脚本',
    'task_desc' => '教育培训付费帖子刷新脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/bang_vip/cron/bang_vip_refresh_queue.php\'',
    'expected_execution_time' => '400',
    'task_interval' => '*/6****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  110 => 
  array (
    'id' => '227',
    'task_name' => 'FUWU-教育培训过期帖子下线脚本',
    'task_desc' => '教育培训过期帖子下线脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/bang_vip/cron/bang_vip_expired_order_queue.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '*/6****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  111 => 
  array (
    'id' => '228',
    'task_name' => 'SEC-【二手TAG】计算二手各个tag发帖数量',
    'task_desc' => '计算二手各个tag发帖数量',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/dev/tag/get_post_num.php\'',
    'expected_execution_time' => '35000',
    'task_interval' => '200***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  112 => 
  array (
    'id' => '229',
    'task_name' => 'SEC-【短信询价】二手短信询价统计报表',
    'task_desc' => '二手短信询价统计报表',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/secondmarket/sms_tongji_day.php\'',
    'expected_execution_time' => '180',
    'task_interval' => '100***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  113 => 
  array (
    'id' => '230',
    'task_name' => 'SEC-【手机品牌型号 】价格区间和帖子数量统计',
    'task_desc' => '价格区间和帖子数量统计',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/secondmarket/mobile/PriceDuringAndPostCountStat.class.php > /tmp/PriceDuringAndPostCountStat.log\'',
    'expected_execution_time' => '32400',
    'task_interval' => '100**1',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  114 => 
  array (
    'id' => '231',
    'task_name' => 'SEC-【手机品牌型号 】正排表、倒排表组建',
    'task_desc' => '正排表、倒排表组建',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/secondmarket/mobile/DictsAndInvertedTableBuilder.class.php > /tmp/DictsAndInvertedTableBuilder.log\'',
    'expected_execution_time' => '32400',
    'task_interval' => '100**2',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  115 => 
  array (
    'id' => '232',
    'task_name' => 'SEC-【手机品牌型号】品牌发帖量统计',
    'task_desc' => '品牌发帖量统计',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/secondmarket/mobile/brand_post_num.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '06**1',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  116 => 
  array (
    'id' => '233',
    'task_name' => 'APO-同步CA日志',
    'task_desc' => '同步CA日志',
    'task_content' => 'sudo -u apollo /bin/bash -c \'/bin/bash /data/apollo/apollo_agent/Scr/rsyncCAlog.sh\'',
    'expected_execution_time' => '230',
    'task_interval' => '5,35****',
    'sudo_user' => 'apollo',
    'hostlist' => 'jxq-sys-dns-03',
  ),
  117 => 
  array (
    'id' => '234',
    'task_name' => 'MYAD-定向-在线',
    'task_desc' => '定向在线数据',
    'task_content' => '/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/misc/union_ad/cron/self_direction_online_import.php',
    'expected_execution_time' => '800',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  118 => 
  array (
    'id' => '235',
    'task_name' => 'SEC-【自动刷新】二手帖子自动刷新脚本',
    'task_desc' => '二手帖子自动刷新脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/secondmarket/AutoRefreshUserPostForSecondmarket.php > /tmp/ershou1.log\'',
    'expected_execution_time' => '1800',
    'task_interval' => '02***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  119 => 
  array (
    'id' => '236',
    'task_name' => 'SEC-【自动刷新】二手帖子自动刷新脚本统计邮件',
    'task_desc' => '二手帖子自动刷新脚本统计邮件',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/secondmarket/RefreshUserPostLogStat.php > /tmp/ershou2.log 2>&1\'',
    'expected_execution_time' => '5000',
    'task_interval' => '02***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  121 => 
  array (
    'id' => '238',
    'task_name' => 'CHE-【百度合作】拼车帖子',
    'task_desc' => '拼车帖子导出',
    'task_content' => 'sudo -u www /bin/bash -c \'/bin/bash /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/pinche.sh\'',
    'expected_execution_time' => '5400',
    'task_interval' => '0*/3***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  122 => 
  array (
    'id' => '239',
    'task_name' => 'FUWU-汇总上一周的店铺pv',
    'task_desc' => '每周一凌晨1点执行。 导入上一周的店铺pv',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/import_pv_report_weekly.php\'',
    'expected_execution_time' => '1800',
    'task_interval' => '01**1',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  124 => 
  array (
    'id' => '241',
    'task_name' => 'FUWU-修复服务店铺uc问题丢失数据脚本',
    'task_desc' => '修复服务店铺uc问题丢失数据脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/addShop2Uc.php\'',
    'expected_execution_time' => '2000',
    'task_interval' => '132***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  125 => 
  array (
    'id' => '242',
    'task_name' => 'FUWU-帮帮置顶预约刷新',
    'task_desc' => '帮帮置顶预约刷新',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/cron/bang/sticky_auto_refresh.php\'',
    'expected_execution_time' => '300',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  131 => 
  array (
    'id' => '248',
    'task_name' => 'CHE-【统计报表】店铺活跃度',
    'task_desc' => '车辆店铺活跃度',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/tuiguang/vehicle_bang/cron/bang_active_info.php\'',
    'expected_execution_time' => '5400',
    'task_interval' => '04***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  132 => 
  array (
    'id' => '249',
    'task_name' => 'CHE-【统计报表】二手车不同类型的在线帖数量统计',
    'task_desc' => '二手车不同类型的在线帖数量统计',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/ershouche_post_type_count.php\'',
    'expected_execution_time' => '5400',
    'task_interval' => '03***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  134 => 
  array (
    'id' => '251',
    'task_name' => 'FANG-楼盘名称匹配',
    'task_desc' => '楼盘名称匹配数据准备',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/loupan/name_autocomplete.php\'',
    'expected_execution_time' => '10800',
    'task_interval' => '5023***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  135 => 
  array (
    'id' => '253',
    'task_name' => 'FANG-小区名称匹配',
    'task_desc' => '小区',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/cron/xiaoqu/gen_xiaoqu_autocomplete.php\'',
    'expected_execution_time' => '21600',
    'task_interval' => '102***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  136 => 
  array (
    'id' => '254',
    'task_name' => 'FANG-免费帖刷新报表',
    'task_desc' => '统计免费帖刷新次数，发送email给相关负责人',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /data/server/www/ganji/ganji_online/ganji_v5/cron/housing/RefreshUserPostLogStat.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '13***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  137 => 
  array (
    'id' => '255',
    'task_name' => 'FANG-出租房自动刷新',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/RentAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '0*/4***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  138 => 
  array (
    'id' => '256',
    'task_name' => 'MSC-msapi帖子图片下载',
    'task_desc' => '对外合作远程下载图片，并执行帖子图片更新',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/msapi/cron/msapi_download_image.php\'',
    'expected_execution_time' => '1800',
    'task_interval' => '*/5****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  139 => 
  array (
    'id' => '257',
    'task_name' => 'FANG-合租房自动刷新',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/ShareAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '50****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  140 => 
  array (
    'id' => '258',
    'task_name' => 'FANG-二手房自动刷新',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/SellAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '35*/5***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  141 => 
  array (
    'id' => '259',
    'task_name' => 'FANG-商铺出租',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/StorerentAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '25****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  142 => 
  array (
    'id' => '260',
    'task_name' => 'FANG-商铺出售',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/StoretradeAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '27****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  143 => 
  array (
    'id' => '261',
    'task_name' => 'FANG-写字楼出租',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/OfficerentAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '29****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  144 => 
  array (
    'id' => '262',
    'task_name' => 'FANG-写字楼出售',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/OfficetradeAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '31****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  145 => 
  array (
    'id' => '263',
    'task_name' => 'FANG-厂房刷新',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/PlantAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '33****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  146 => 
  array (
    'id' => '264',
    'task_name' => 'FANG-楼盘刷新',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/housing/LoupanAutoRefresh.php > /dev/null\'',
    'expected_execution_time' => '3600',
    'task_interval' => '55****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  147 => 
  array (
    'id' => '265',
    'task_name' => 'FANG-地铁公交自动更新',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/bin/bash /server/www/ganji/ganji_online/ganji_v5/cron/housing/report/sqlite/BusSubway.sh > /server/www/ganji/ganji_online/ganji_v5/cron/housing/report/sqlite/result 2>&1\'',
    'expected_execution_time' => '7200',
    'task_interval' => '0103**1',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  148 => 
  array (
    'id' => '266',
    'task_name' => 'FANG-抓取二手房均价',
    'task_desc' => '链家、soufun',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/GetLjdcPrice.class.php > /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/resultGrab.txt && /usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/GetSoufangPrice.class.php >> /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/resultGrab.txt && /usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/GrabPriceWatch.class.php\'',
    'expected_execution_time' => '7200',
    'task_interval' => '0051,15**',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  149 => 
  array (
    'id' => '267',
    'task_name' => 'FANG-二手房均价计算',
    'task_desc' => 'RT',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/HouseMassage.class.php > /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/result.txt && /usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/HouseSourceExist.class.php >> /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/result.txt && /usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/xiaoqu/sell_avgPrice/ModifyXiaoqu.class.php\'',
    'expected_execution_time' => '7200',
    'task_interval' => '10011,15**',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  150 => 
  array (
    'id' => '268',
    'task_name' => 'FANG-重复预约',
    'task_desc' => '新版在推广期内重复预约',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/housing/premier/script/HouseBookingNextDayRefresh_v2.php -process 16\'',
    'expected_execution_time' => '3600',
    'task_interval' => '100***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  151 => 
  array (
    'id' => '269',
    'task_name' => 'FANG-自助购买刷新次数计算',
    'task_desc' => '减刷新次数',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/housing/premier/script/HousingAssureRefreshDecrease.class.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '20***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  152 => 
  array (
    'id' => '270',
    'task_name' => 'FANG-房源过期下线',
    'task_desc' => '放心房',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/housing/premier/script/HousingAssureExpire.class.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '30***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  153 => 
  array (
    'id' => '271',
    'task_name' => 'MYAD-定向检查删除的帖子',
    'task_desc' => '定向检查删除的帖子',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/dev/sticky/self_direction_util.php checkpoststatus\'',
    'expected_execution_time' => '600',
    'task_interval' => '02***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  154 => 
  array (
    'id' => '272',
    'task_name' => 'MYAD-检查redis的帖子变化',
    'task_desc' => '检查redis的帖子变化',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_service/check_post.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '20*/2***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  155 => 
  array (
    'id' => '273',
    'task_name' => 'MYAD-竞价-上线脚本2',
    'task_desc' => '竞价-上线脚本2',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_bidding/biddingPostOnline.cron.php yesterday\'',
    'expected_execution_time' => '1000',
    'task_interval' => '101-2***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  156 => 
  array (
    'id' => '275',
    'task_name' => 'JIAOYOU-EDM同城推荐',
    'task_desc' => '注册后的第15天，30天，45天……15n（n为正整数，n≥1）发送，邮箱验证成功用户',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php  /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_city_match.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '011***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  157 => 
  array (
    'id' => '276',
    'task_name' => 'JIAOYOU-EDM每周推荐',
    'task_desc' => '验证时间+3为第一次发送时间，以后每次发送均以7天为一个周期,邮箱验证成功用户',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php  /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_week_match.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '00***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  158 => 
  array (
    'id' => '277',
    'task_name' => 'JIAOYOU-EDM关注功能刺激使用',
    'task_desc' => '注册成功且邮箱验证成功
超过14天没使用过发送私信和打招呼功能用户
不使用此功能第16天、第31天、第61天发送此邮件',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_follow_motivate.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '01***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  159 => 
  array (
    'id' => '278',
    'task_name' => 'JIAOYOU-EDM私信打招呼功能刺激使用',
    'task_desc' => '注册成功且邮箱验证成功
超过14天没使用过发送私信和打招呼功能用户
不使用此功能第15天、第30天、第45天、第60天发送此邮件',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_send_message_motivate.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '03***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  160 => 
  array (
    'id' => '279',
    'task_name' => 'JIAOYOU-EDM形象照引导上传',
    'task_desc' => '成功上传生活照但是没有设置形象照,上传生活照后的第2天、第8天、第26天、第60天发送此邮件',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_upload_avatar_guide.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '04***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  161 => 
  array (
    'id' => '280',
    'task_name' => 'JIAOYOU-EDM生活照引导上传',
    'task_desc' => '邮箱验证成功后没有上传生活照，则验证成功后第3天、第10天、第24天、第60天进行发送',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_upload_photo_guide.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '05***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  162 => 
  array (
    'id' => '281',
    'task_name' => 'JIAOYOU-EDM最近关注',
    'task_desc' => '验证时间+4为第一次发送时间，以后每次发送均以7天为一个周期
发送周期内无人关注则不发送，若周期内有人关注，则发送任意一名关注者信息，确保周期只发送一封此类邮件',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php  /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_focusnotice.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '06***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  163 => 
  array (
    'id' => '282',
    'task_name' => 'JIAOYOU-EDM用户私信',
    'task_desc' => '用户私信提醒edm',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php  /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_pmnotice.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '07***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  164 => 
  array (
    'id' => '283',
    'task_name' => 'JIAOYOU-EDM新手指南',
    'task_desc' => '邮箱验证未成功用户',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_beginnerguide.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '08***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  165 => 
  array (
    'id' => '284',
    'task_name' => 'JIAOYOU-EDM赶集交友情缘报告',
    'task_desc' => '注册成功且邮箱验证成功		
一周内得到过任何互动信息，私信、关注以及以后的提问用户
邮箱验证成功+8为第一次发送时间，以后每次发送均以7天为一个周期',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_luck.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '09***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  166 => 
  array (
    'id' => '285',
    'task_name' => 'JIAOYOU-EDM同月同日生推荐',
    'task_desc' => '邮箱验证成功用户',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_birthday_match.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '010***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  167 => 
  array (
    'id' => '286',
    'task_name' => 'JIAOYOU-EDM发送激活手机',
    'task_desc' => '用户注册或激活交友频道成功
注册或激活交友后14天未进行手机验证',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php  /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_mobilereg.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '011***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  168 => 
  array (
    'id' => '287',
    'task_name' => 'JIAOYOU-EDM速配推荐',
    'task_desc' => '用户验证成功24小时后发送此邮件',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php  /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_rapid_match.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '012***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  169 => 
  array (
    'id' => '288',
    'task_name' => 'JIAOYOU-EDM资料完善提醒',
    'task_desc' => '邮件发送与激活间隔时间 7 天',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_notice.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '013***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  170 => 
  array (
    'id' => '289',
    'task_name' => 'JIAOYOU-EDMTA是你喜欢的类型',
    'task_desc' => '注册成功且邮箱验证成功
用户 7，21，90 天未登录时，发送此EDM',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php  /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_mjsp.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '014***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  171 => 
  array (
    'id' => '290',
    'task_name' => 'JIAOYOU-EDM马甲用户访问以及打分EDM',
    'task_desc' => '马甲用户访问以及打分EDM',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php  /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_visit.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '015***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  172 => 
  array (
    'id' => '291',
    'task_name' => 'JIAOYOU-EDM赶集交友丘比特之箭',
    'task_desc' => '注册成功且邮箱验证成功		
择偶条件设置年龄、身高、婚姻状况的用户  （因为年龄、身高、婚姻都有默认值，所以婚姻这个没法判断，前边两个只匹配默认值）
设置成功或者验证成功时间+2为第一次发送时间，以后每次发送均以7天为一个周期',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/edm_jiaoyou_cupid.php\'',
    'expected_execution_time' => '36000',
    'task_interval' => '016***',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  173 => 
  array (
    'id' => '292',
    'task_name' => 'JIAOYOU-收费服务开通下线',
    'task_desc' => '扫描用户服务，更改用户当前服务状态，进行开通或下线操作',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/cron_service_scan_script.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/5****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  174 => 
  array (
    'id' => '295',
    'task_name' => 'JIAOYOU-DAEMON会员中心信息同步1',
    'task_desc' => '会员中心更新同步到交友',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_uc.php --type=1\'',
    'expected_execution_time' => '7200',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  175 => 
  array (
    'id' => '296',
    'task_name' => 'JIAOYOU-DAEMON会员中心信息同步2',
    'task_desc' => '会员中心信息同步到交友',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_uc.php --type=2\'',
    'expected_execution_time' => '7200',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  176 => 
  array (
    'id' => '297',
    'task_name' => 'JIAOYOU-DAEMON编辑后台审核结果通知1',
    'task_desc' => '编辑后台个人相关信息审核结果通知',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_audit.php --type=1\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  177 => 
  array (
    'id' => '298',
    'task_name' => 'JIAOYOU-DAEMON编辑后台审核结果通知2',
    'task_desc' => '编辑后台审核结果通知',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_audit.php --type=2\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  178 => 
  array (
    'id' => '299',
    'task_name' => 'JIAOYOU-DAEMON用户信息审核通过',
    'task_desc' => '对用户审核通过的信息进行处理',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_audit_success.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  179 => 
  array (
    'id' => '301',
    'task_name' => 'JIAOYOU-DAEMON发送私信',
    'task_desc' => '发送私信',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_message.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  180 => 
  array (
    'id' => '302',
    'task_name' => 'JIAOYOU-DAEMON通知用户发信箱已读',
    'task_desc' => '通知用户发件箱已读邮件',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_message_outbox_setRead.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  181 => 
  array (
    'id' => '303',
    'task_name' => 'JIAOYOU-DAEMON后台发送系统私信',
    'task_desc' => '后台发送系统私信',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_send_sysmsg.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  182 => 
  array (
    'id' => '304',
    'task_name' => 'JIAOYOU-DAEMON交友手机端登录用户同步',
    'task_desc' => '交友手机端登录用户同步',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_mobile_login.php\'',
    'expected_execution_time' => '7200',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  183 => 
  array (
    'id' => '305',
    'task_name' => 'JIAOYOU-DAEMON发送新注册用户',
    'task_desc' => '发送新注册用户',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_send_newreg_notice.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  184 => 
  array (
    'id' => '306',
    'task_name' => 'JIAOYOU-DAEMON实名认证同步',
    'task_desc' => '会员中心实名认证同步',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_cardserver_2_jiaoyou.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  185 => 
  array (
    'id' => '307',
    'task_name' => 'JIAOYOU-DAEMON视频订单回调',
    'task_desc' => '视频订单回调',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/cron_showlive_callback.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  186 => 
  array (
    'id' => '308',
    'task_name' => 'MYAD-公共-用户数据',
    'task_desc' => '公共-用户数据',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/self_service/self_service_user_info.php\'',
    'expected_execution_time' => '120',
    'task_interval' => '0*/1***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  187 => 
  array (
    'id' => '309',
    'task_name' => 'APO-上周发布任务详情',
    'task_desc' => '上周完成任务TOP，上周发任务耗时统计邮件功能',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/curl http://release.apollo.corp.ganji.com/Task/TaskSendMail/sendMailForWeekOrMonth/type/week\'',
    'expected_execution_time' => '2',
    'task_interval' => '252**1',
    'sudo_user' => 'www',
    'hostlist' => 'yz-apollo-web-02',
  ),
  188 => 
  array (
    'id' => '310',
    'task_name' => 'APO-上月发布任务详情',
    'task_desc' => '上月完成任务TOP，上月发任务耗时统计邮件功能',
    'task_content' => 'sudo -u www /bin/bash -c \'/opt/lampp/bin/curl http://release.apollo.corp.ganji.com/Task/TaskSendMail/sendMailForWeekOrMonth/type/month\'',
    'expected_execution_time' => '2',
    'task_interval' => '2621**',
    'sudo_user' => 'www',
    'hostlist' => 'yz-apollo-web-02',
  ),
  189 => 
  array (
    'id' => '311',
    'task_name' => 'CHE-【免费店铺】im召回',
    'task_desc' => '针对不活跃的免费店铺实行im召回策略',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/free_bang_send_im.php\'',
    'expected_execution_time' => '1200',
    'task_interval' => '03**5',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  190 => 
  array (
    'id' => '312',
    'task_name' => 'FANG-小区统计信息(bj)',
    'task_desc' => '小区统计信息',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/cron/xiaoqu/stat_house_num.php bj > /dev/null\'',
    'expected_execution_time' => '86400',
    'task_interval' => '200***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  191 => 
  array (
    'id' => '313',
    'task_name' => 'APO-checkCTService',
    'task_desc' => 'checkCTService',
    'task_content' => 'sudo -u apollo /bin/bash -c \'/bin/bash  /data/apollo/apollo_agent/Scr/checkCTService.sh\'',
    'expected_execution_time' => '3',
    'task_interval' => '*/3****',
    'sudo_user' => 'apollo',
    'hostlist' => 'jxq-oa-web-01,jxq-sys-dns-03,nh-ms-web-sim01,yz-apollo-web-02,yz-ms-web-02,yz-sys-bak-04',
  ),
  192 => 
  array (
    'id' => '316',
    'task_name' => 'CHE-【免费店铺】短信召回',
    'task_desc' => '1.当前时间之前一周内开通免费店铺的用户。 
2.有效贴（除防垃圾或编辑删除的帖子以外的所有帖子）大于等于2条。 
3.刷新使用总量低于3次。 
4.给认证的手机号下发短信。 
5.下发频次：1次',
    'task_content' => '/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/vehicle/free_bang_recall.php',
    'expected_execution_time' => '2400',
    'task_interval' => '3011**1',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  193 => 
  array (
    'id' => '317',
    'task_name' => 'APO-检查为root的文件',
    'task_desc' => '检查为root的文件',
    'task_content' => 'sudo -u www /bin/bash -c \'/bin/bash /data/Script/script_project/checkFilesOwn.sh\'',
    'expected_execution_time' => '60',
    'task_interval' => '23****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-apollo-web-02',
  ),
  194 => 
  array (
    'id' => '318',
    'task_name' => 'ZP-统一审核队列',
    'task_desc' => '招聘付费帖统一审核队列获取',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_audit/audit_ad_queue.php 512_1024_2048_4096\'',
    'expected_execution_time' => '4000',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  195 => 
  array (
    'id' => '319',
    'task_name' => 'MYAD-公共-统一审核队列处理',
    'task_desc' => '公共-统一审核队列处理',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_audit/audit_ad_queue.php 1_2_4_16\'',
    'expected_execution_time' => '700',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  196 => 
  array (
    'id' => '320',
    'task_name' => 'SEC-【二手帮帮】读取广告审核通过队列',
    'task_desc' => '二手帮帮读取广告审核通过队列',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_audit/audit_ad_queue.php 16384_32768\'',
    'expected_execution_time' => '900',
    'task_interval' => '*/1****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  197 => 
  array (
    'id' => '323',
    'task_name' => 'JIAOYOU-DAEMON浏览历史1',
    'task_desc' => '看过我，我看过',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_jiaoyou_visit.php --type=1\'',
    'expected_execution_time' => '7200',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  198 => 
  array (
    'id' => '324',
    'task_name' => 'JIAOYOU-DAEMON浏览历史2',
    'task_desc' => '浏览历史',
    'task_content' => 'sudo -u ganji /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/queue_jiaoyou_visit.php --type=2\'',
    'expected_execution_time' => '7200',
    'task_interval' => '*/1****',
    'sudo_user' => 'ganji',
    'hostlist' => 'yz-ms-web-02',
  ),
  199 => 
  array (
    'id' => '325',
    'task_name' => 'FANG-小区统计信息(sh)',
    'task_desc' => '小区统计信息(sh)',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/cron/xiaoqu/stat_house_num.php sh > /dev/null\'',
    'expected_execution_time' => '86400',
    'task_interval' => '200***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  200 => 
  array (
    'id' => '326',
    'task_name' => 'FANG-小区统计信息(cd)',
    'task_desc' => '小区统计信息(cd)',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/cron/xiaoqu/stat_house_num.php cd > /dev/null\'',
    'expected_execution_time' => '86400',
    'task_interval' => '200***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  201 => 
  array (
    'id' => '327',
    'task_name' => 'FANG-小区统计信息(gz)',
    'task_desc' => '小区统计信息(gz)',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/cron/xiaoqu/stat_house_num.php gz > /dev/null\'',
    'expected_execution_time' => '86400',
    'task_interval' => '200***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  202 => 
  array (
    'id' => '328',
    'task_name' => 'FANG-小区统计信息(nj)',
    'task_desc' => '小区统计信息(nj)',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/cron/xiaoqu/stat_house_num.php nj > /dev/null\'',
    'expected_execution_time' => '86400',
    'task_interval' => '200***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  203 => 
  array (
    'id' => '329',
    'task_name' => 'FANG-小区统计信息(other)',
    'task_desc' => '小区统计信息(other)',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/cron/xiaoqu/stat_house_num.php -v bj sh gz cd nj > /dev/null\'',
    'expected_execution_time' => '86400',
    'task_interval' => '200***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  204 => 
  array (
    'id' => '330',
    'task_name' => 'FUWU-建材排行榜',
    'task_desc' => 'http://bj.ganji.com/jiancaimall/ 跑出大师写的pv数据',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/product_pv.php\'',
    'expected_execution_time' => '600',
    'task_interval' => '**/12***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  205 => 
  array (
    'id' => '331',
    'task_name' => 'BI-商业指标-自助置顶',
    'task_desc' => 'crontab：自助置顶商业指标定时脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_analysis/calculateSticky.cron.php\'',
    'expected_execution_time' => '7200',
    'task_interval' => '009***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  206 => 
  array (
    'id' => '332',
    'task_name' => 'BI-商业指标-定向推广',
    'task_desc' => 'crontab：定向推广商业指标定时脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_analysis/calculateDirection.new.cron.php\'',
    'expected_execution_time' => '9000',
    'task_interval' => '009***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  207 => 
  array (
    'id' => '333',
    'task_name' => 'BI-商业指标-竞价',
    'task_desc' => 'crontab：竞价商业指标定时脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_analysis/calculateBidding.cron.php\'',
    'expected_execution_time' => '7200',
    'task_interval' => '009***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  208 => 
  array (
    'id' => '334',
    'task_name' => 'BI-商业指标-小类推广',
    'task_desc' => 'crontab：小类推广商业指标定时脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_analysis/calculateMinorCateSpread.cron.php\'',
    'expected_execution_time' => '7200',
    'task_interval' => '009***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  209 => 
  array (
    'id' => '335',
    'task_name' => 'BI-商业产品-58置顶价格入库',
    'task_desc' => '将爬虫组抓取的58置顶价格入库',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_analysis/countSticky58Price.cron.php\'',
    'expected_execution_time' => '7200',
    'task_interval' => '001*/14**',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  210 => 
  array (
    'id' => '337',
    'task_name' => 'FANG-清除推广房源',
    'task_desc' => '将3个月前发布并推广的房源取消推广',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/housing/premier/script/HousingCancelPremierPost.php\'',
    'expected_execution_time' => '1800',
    'task_interval' => '150***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  211 => 
  array (
    'id' => '338',
    'task_name' => 'FUWU--统一审核-服务付费店铺',
    'task_desc' => '服务类目付费店铺统一审核脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/app/service_store/cron/service_audit_2_ad_queue.php\'',
    'expected_execution_time' => '800',
    'task_interval' => '*****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  212 => 
  array (
    'id' => '339',
    'task_name' => 'FUWU--统一审核-教育付费贴',
    'task_desc' => '教育类目付费贴统一审核脚本',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/ad_audit/audit_ad_queue.php 256 5\'',
    'expected_execution_time' => '800',
    'task_interval' => '*****',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  213 => 
  array (
    'id' => '340',
    'task_name' => 'APO-CA数据每日汇总',
    'task_desc' => 'CA的数据按照省市运营商idc进行当然汇总',
    'task_content' => 'sudo -u apollo /bin/bash -c \'/usr/bin/python /data/apollo/script/cron/daylyaggregate.py\'',
    'expected_execution_time' => '60',
    'task_interval' => '01***',
    'sudo_user' => 'apollo',
    'hostlist' => 'jxq-sys-dns-03',
  ),
  214 => 
  array (
    'id' => '341',
    'task_name' => 'FUWU--监控-审核异常数据',
    'task_desc' => '统一审核异常数据监控，便于定位',
    'task_content' => '/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/ganji_v5/cron/service_store/MoniterExceptionData.php',
    'expected_execution_time' => '800',
    'task_interval' => '018,13,18***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  215 => 
  array (
    'id' => '344',
    'task_name' => 'MSC-统计每日会员中心总余额和总冻结金额',
    'task_desc' => '统计每日会员中心总余额和总冻结金额',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji_v3/apps/pay/cron/balance_statistics.php\'',
    'expected_execution_time' => '60',
    'task_interval' => '00***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-sys-bak-04',
  ),
  216 => 
  array (
    'id' => '346',
    'task_name' => 'JIAOYOU-数据统计脚本',
    'task_desc' => '统计用户相关数据',
    'task_content' => 'sudo -u www /bin/bash -c \'/usr/local/webserver/php/bin/php /server/www/ganji/ganji_online/jiaoyou/app/cron/statistics/cron_data_statistics.php\'',
    'expected_execution_time' => '3600',
    'task_interval' => '00***',
    'sudo_user' => 'www',
    'hostlist' => 'yz-ms-web-02',
  ),
  217 => 
  array (
    'id' => '350',
    'task_name' => 'APO-1234天赋是否',
    'task_desc' => '测试',
    'task_content' => 'sudo -u apollo /bin/bash -c \'/usr/local/webserver/php/bin/php /data/Script/Cron/bsm_test.php\'',
    'expected_execution_time' => '1',
    'task_interval' => '*****',
    'sudo_user' => 'apollo',
    'hostlist' => 'jxq-oa-web-01,yz-bak-ku-04,yz-sys-bak-04',
  ),
  218 => 
  array (
    'id' => '351',
    'task_name' => 'APO-cs',
    'task_desc' => 'cs',
    'task_content' => '1',
    'expected_execution_time' => '1',
    'task_interval' => '*****',
    'sudo_user' => 'apollo',
    'hostlist' => 'yz-sys-bak-04',
  ),
) ?>